#pragma once

extern bool SigValid;
extern const char* InvalidSig;

extern void* SigPlayer_State_KnuxGlideLeft();
extern void* SigPlayer_State_ChargeHammerDash();
extern void* SigCamera_ShakeScreen();
extern void* Sigsub_1403A2550();
extern void* SigIsMirrorMode();
extern void* SigSpecialClear_State_FigureOutWhatToDoNext_D0();
extern void* SigPlayer_Create_266();
extern void* SigActClear_Create();
extern void* Sigsub_140302180();
extern void* SigS3K_CompElement_Draw();
extern void* SigS3K_CompElement_State_Carousel();
extern void* SigS3K_CompElement_Create();
extern void* SigLevelSelect_State_Navigate();
extern void* SigPlayer_State_HammerDash();
extern void* SigPlayer_HandleGroundRotation();
extern void* SigPlayer_State_Roll();
extern void* SigPlayer_State_Air();
extern void* SigLinkGameLogicDLL();
extern void* SigPlayer_StaticLoad();
extern void* SigShield_State_Insta();
extern void* SigPlayer_State_DropDash();
extern void* SigNotifyCallback();
extern void* SigCopyPalette();
extern void* SigPlayer_StageLoad();
extern void* Sigsub_140187AC0();
extern void* SigStarPost_EnterGachaponBonus();
extern void* SigStarPost_EnterGlowingSpheresBonus();
extern void* SigStarPost_EnterSlotBonus();
extern void* SigStarPost_BonusStars();
extern void* SigMusic_FadeToStop();
extern void* SigPlayer_State_Hurt();
extern void* SigPlayer_State_GlideRight();
extern void* SigPlayer_State_Ground();
extern void* SigPlayer_Gravity_False();
extern void* SigPlayer_Action_Jump();
extern void* SigPlayer_Action_CarryPlayer();
extern void* SigPlayer_State_Carried();
extern void* SigPlayer_Action_DblJumpSonic();
extern void* SigPlayer_Input_AI_Follow();
extern void* SigPlayer_DoHyperDash();
extern void* SigShield_Create();
